# Puerto en que corre la aplicación (Spring Boot por defecto usa 8080)
server.port=8080

# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://192.168.100.168:3306/MqttBase
spring.datasource.username=usermqtt
spring.datasource.password=${DB_PASSWORD:Mqtt1234!}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA/Hibernate
# Con esta linea  le indicamos a Hibernate que use el dialecto de MySQL.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Desactivar el cache de plantillas Thymeleaf para desarrollo
spring.thymeleaf.cache=false

# Intervalo en milisegundos para enviar actualizaciones al dashboard
broadcast.fixed-rate-ms=1000
